### ISSUE TITLE
VAT Validation - WSDL

### ISSUE THREAD

**Issue by versedi** [Inchoo/Inchoo_PHP7#10]
VAT Validation is not working in PHP7.

I'm pretty sure @schmengler explained here:
http://magento.stackexchange.com/a/88160/13907

Quote: 
"(...) PHP 7 incompatibility in Zend_XmlRpc_Server has been fixed in Zend Framework 1.12.12

http://framework.zend.com/changelog/1.12.12
https://github.com/zendframework/zf1/pull/540

All versions prior CE 1.9.2.2 / EE 1.14.2.2 use an older version of Zend Framework, thus might have problems if you use the XML-RPC API of Magento."

**Comment by icurdinj** [comment]
Good to know. As we already said, this extension is meant to bring M CE 1.9.2.2 to PHP 7 compatibility. 
If someone wants to try for older versions, or EE, please fork and make a pull request. We could make a separate release for such cases.

**Comment by ivanweiler** [comment]
Vat validation is working for me on php7. Also, Mage_Customer_Helper_Data::checkVatNumber() is using native php soap, so it's not Zend related.

@versedi Maybe issue you're having is something similar to this?
http://stackoverflow.com/questions/21861077/soap-error-parsing-wsdl-couldnt-load-from-but-works-on-wamp

Ofc, it's possible that it's acting differently on different setups, I'll report if I manage to reproduce the issue.

**Comment by versedi** [comment]
I've setup a fresh vagrant with PHP 7.0.0 and new instance of Magento on another PC.

Can't reproduce this bug here either. 

The only thing that comes to my mind that could cause this is a coincidence - in the two moments of testing the server could be unavailable so it was resolved with error every time the VAT was checked or there was some sort of internet connection error on my side.

I'm confirming that VAT Validation works on PHP 7.0.

Thank you for your interest and sorry for the confusion.

**Comment by ivanweiler** [comment]
Glad to hear it's working! Thanks for letting us know
