### ISSUE TITLE
Syntax Check in PHP 7.0.14 and complete Magento 1.9.3.1

### ISSUE THREAD

**Issue by simkea** [Inchoo/Inchoo_PHP7#100]
Hello, 
can you add your patch complete and fix also this Error messages?

#PHP Fatal error:  'break' not in the 'loop' or 'switch' context in ./app/code/core/Mage/Adminhtml/Model/Extension.php on line 370
#PHP Parse error:  syntax error, unexpected 'new' (T_NEW) in ./lib/Varien/Pear/Registry.php on line 49
#PHP Parse error:  syntax error, unexpected 'new' (T_NEW) in ./lib/PEAR/XML/Unserializer.php on line 801
#PHP Parse error:  syntax error, unexpected 'new' (T_NEW) in ./lib/PEAR/XML/Parser.php on line 616

i have used this command to find all syntax error in the complete magento folder:
find . -name "*.php" -exec php -l {} \; 1>/dev/null

br|thx

**Comment by icurdinj** [comment]
Please take a look at this: https://github.com/Inchoo/Inchoo_PHP7/wiki/NewInLib
There is some dead code in Magento libraries, and there is no point in fixing something that's not used at all. If you have an example of where this stuff is actually used (or could be used) in actual Magento workflow, then, of course we'll try to fix it.

**Comment by TheGamesmenDev** [comment]
The only time I've had this become an issue is when using OpCache and running Compile All
