### ISSUE TITLE
Blank Screen After switching to PHP 7.0 on CentOS 6

### ISSUE THREAD

**Issue by farbulous** [Inchoo/Inchoo_PHP7#101]
After applying the Inchoo PHP7 patch, all is great.  No errors.  Then when I switch the PHP version from 5.6 to 7.0 for the site, the pages are all blank.  Backend and front end.  Any help is greatly appreciated.

**Comment by icurdinj** [comment]
First of all, enable error reporting, so you get some useful message instead of blank pages.
Also see: https://github.com/Inchoo/Inchoo_PHP7/wiki/ProperInstallation
