### ISSUE TITLE
Uncaught Error: Function name must be a string in lib/Varien/File/Uploader.php:274

### ISSUE THREAD

**Issue by JensBourgeois** [Inchoo/Inchoo_PHP7#102]
Hello,

I get the following error when trying to upload an image in Catalog > Manage Products.

Using:
- Magento v1.9.1.0
- Inchoo_PHP7 "1.9.2.4" branch

<b>Fatal error</b>:  Uncaught Error: Function name must be a string in lib/Varien/File/Uploader.php:274
Stack trace:
#0 lib/Varien/File/Uploader.php(187): Varien_File_Uploader-&gt;_validateFile()
#1 app/code/core/Mage/Adminhtml/controllers/Catalog/Product/GalleryController.php(46): Varien_File_Uploader-&gt;save('/Applications/M...')
#2 app/code/core/Mage/Core/Controller/Varien/Action.php(418): Mage_Adminhtml_Catalog_Product_GalleryController-&gt;uploadAction()
#3 app/code/core/Mage/Core/Controller/Varien/Router/Standard.php(254): Mage_Core_Controller_Varien_Action-&gt;dispatch('upload')
#4 app/code/core/Mage/Core/Controller/Varien/Front.php(172): Mage_Core_Controller_Varien_Router_Standard-&gt;match(Object(Mage_Core_Controller_Request_Http))
#5 lib/Varien/File/Uploader.php</b> on line <b>274</b><br />

Explanation can be found here:
http://magento.stackexchange.com/questions/105550/how-can-solve-error-magento-1-xx-on-php-7/105604#105604

Seems to be the same issue that was fixed for Mage_ImportExport_Model_Import_Uploader but now in the lib uploader.
Can this be added to the extension?

Thanks!

**Comment by icurdinj** [comment]
That should be fixed, unless there is some difference between 1.9.1 and 1.9.2 there - we havent tested on 1.9.1 yet. (Though we probably will, at some point.)
In the meantime, can you just check first that the extension is properly installed?

**Comment by JensBourgeois** [comment]
Sorry, I am using Magento ver. 1.8.1.0.
I don't know if that makes any difference?
I am quite sure the module is installed correctly.

**Comment by icurdinj** [comment]
It could be a conflict with another module which overwrites the same class, but it's difficult to say. 1.8 core is definitely not tested with this extension, and you could, potentially, have many more problems with PHP 7. 
Any chance that you could upgrade your core?

**Comment by JensBourgeois** [comment]
Well, the easiest fix is to just copy the lib/Varien/File/Uploader.php to the local codepool and fix the relevant line there.

If we had more time/budget, we could also update the core of course. :)

**Comment by icurdinj** [comment]
Quick & dirty :-) Yeah, that will probably work, but keep an eye out for other stuff, there may be other incompatibilities.
Good luck!
