### ISSUE TITLE
Fatal error: Uncaught Error: Function name must be a string in app\code\core\Mage\Core\Model\Layout.php on line 555

### ISSUE THREAD

**Issue by ajzele** [Inchoo/Inchoo_PHP7#103]
// PHP 5: 
```
$out .= $this->getBlock($callback[0])->$callback[1]();
```

// PHP 7: 
```
$out .= $this->getBlock($callback[0])->{$callback[1]}();
```

**Comment by icurdinj** [comment]
https://github.com/Inchoo/Inchoo_PHP7/wiki/ProperInstallation
or
you are using master branch or 2.* release with a core older than 1.9.3 or 1.14.3. Use branches _1.9.2.4_ or _EE_ instead.

**Comment by ajzele** [comment]
Ah, spot on :) Master branch ... because who reads the docs 👍

**Comment by ajzele** [comment]
Hey @icurdinj I am looking through other branches. Don't see any addressing Mage\Core\Model\Layout.php, you sure you got this case covered?

**Comment by icurdinj** [comment]
Both 1.9.2.4 and EE have Inchoo_PHP7_Model_Layout. Check it out, and config.xml too.

**Comment by mablekos** [comment]
Hi @icurdinj I think a fix need to be added for the Mage\Core\Model\Layout.php which as a file doesn't exist on the 1.9.2.4 branch. Thanks

**Comment by icurdinj** [comment]
@mablekos no, it doesn't because that core layout model is rewritten in Inchoo_PHP7_Model_Layout. That's where the fix is.
