### ISSUE TITLE
Make sorting more consistent [Suggestion]

### ISSUE THREAD

**Issue by jwittorf** [Inchoo/Inchoo_PHP7#104]
Hi,

first of thanks for all the work you've already put in, I'm just starting my first project with PHP7.

Looking for possible bug/troubles etc. I ran across [this blog post](https://www.ecomlane.com/announcements/4/How-to-make-Magento-1923-work-with-PHP-7.html) and I found (almost) all the changes in your module.

There's one change to the `/app/code/core/Mage/Sales/etc/config.xml` to "make sorting more consistent". You can view the changes [here](https://github.com/OpenMage/magento-lts/pull/62/files#diff-4df50d10fd17f62141d3b21fbc10bab2)

Since the [pull request](https://github.com/OpenMage/magento-lts/pull/62) to https://github.com/OpenMage/magento-lts/ is already merged I though this would be something you guys could add to your repository, too. I guess everybody would like to have a "plug & play php7" setup so why don't add another piece.

To be honest I haven't yet add or tested the small change and was hoping to get it with an update directly from your repository and not having to hack in some way by myself. If you'd be willing to add this change, I'd create a pull request.

**Comment by tmotyl** [comment]
Can you describe which part is missing? or even better, provide a pull request?

**Comment by icurdinj** [comment]
@jwittorf , we had that sorting fix in earlier versions, then replaced it with a better one.
