### ISSUE TITLE
Product image uploads error

### ISSUE THREAD

**Issue by L337LUKE** [Inchoo/Inchoo_PHP7#108]
Hey Guys,

I'm trying to upload images to a given product but not having much luck =/.

I'm aware of the problem which requires overwriting the `Varien_File_Uploader` class but the fix that's currently in via you're module doesn't seem to be applying for some reason and subsequently getting the following error. 

`product-one.jpg (99.20 kB)Notice: Array to string conversion in /var/www/public/lib/Varien/File/Uploader.php on line 274`

What's strange is, I can see the module files are installed as shown in the screenshot file below, and the module is enabled in magento + i've done all the usual clearing caches/logging-out/in etc but nada.

![screen shot 2017-03-16 at 15 40 35](https://cloud.githubusercontent.com/assets/4473269/24004720/f3087394-0a5e-11e7-81f6-cfa2c2ebebd5.png)

I know I can copy the file path into the local pool and overwrite the class using that method but that feels dirty to me and I don't really like doing it :(

I'm currently using Magento 1.9.2.4 installed via composer using `firegento/magento : "1.9.2.4-patch4"`

Is there something i'm missing or any rough idea as to what the problem might be?

**Comment by sambolek** [comment]
The rewrite isn't for Varien_File_Uploader, but fit Mage_Core uploaded https://github.com/Inchoo/Inchoo_PHP7/blob/1.9.2.4/app/code/local/Mage/Core/Model/File/Uploader.php#L35

Do you have a custom module for file uploads that extends from Varien_File_Uploader instead of Mage_Core one?

**Comment by L337LUKE** [comment]
I think I wasn't direct enough about the first point in your comment, I know that to extend Varien_File_Uploader you do so through Mage_Core, which is what the Inchoo module is trying to do in that Uploader.php file at line 124. so it is indirectly overwriting Varien_File_Uploader, my bad there.

I did have a module which allowed you to use the media file uploader within a custom widget I was building, however I disabled that as it's the only module which makes use of the uploader and still no joy even after clearing caches/logging out/in again.

**Comment by icurdinj** [comment]
Fortunately, we have an automated testing tool now that might help. Go to `shell` folder, run `php inchoo_php7_test.php` and see what it has to say.

**Comment by L337LUKE** [comment]
Hey @icurdinj 

I get the following, which says that all the tests pass =/

```
$ php inchoo_php7_test.php 
Running tests...
1: CLI version of PHP is Ok: 7.0.6-1+donate.sury.org~trusty+1 (Note that CLI and web server versions of PHP may differ.)
2: Inchoo_PHP7 module is enabled.
3: Inchoo_PHP7 version is: 1.0.7, Magento core version is: Community 1.9.2.4 - Ok.
4: Core helper is rewritten.
5: Core layout model is rewritten.
6: Core import entity product model is rewritten.
7: Core export entity product configurable model is rewritten.
8: Core export entity product grouped model is rewritten.
9: Core export entity product simple model is rewritten.
10: Core export entity customer model is rewritten.
Tests successful: 10/10.
```

**Comment by icurdinj** [comment]
In that case, I would definitely suspect the same problem as @sambolek said: a 3rd party extension overwriting file uploading and using varien file uploader directly.
Either find the offending extension and fix the problem there, or do what you said in the first place - overwrite varien in local folder. Dirty, but should work.
