### ISSUE TITLE
update phpseclib 

### ISSUE THREAD

**Issue by pepijnblom** [Inchoo/Inchoo_PHP7#109]
We just experienced problems with a client's order export using Xtento Sales Export module and it turns out they use the phpseclib library found in the lib/phpseclibrary. 

The library bundled with Magento 1.9.3.2 is not fully PHP7 compatible it seems and overwriting it with the latest version found here solves the problem:
https://github.com/phpseclib/phpseclib/releases/tag/1.0.5

Could this be something you could add to the module?

**Comment by icurdinj** [comment]
It would be a bit too much to include the whole phpseclib, and especially because it solves problems with a 3rd party extension, not Magento core.
Updating phpseclib is, generally, a good idea, though. Just out of scope of this extension.

**Comment by Blackskyliner** [comment]
I guess it could be somehow solved if using composer to manage dependencies and to ensure that the composer autoloader gets called first. This way you could just composer require the latest (known to work with magento) version of phpseclib and let the Autolaoder take care.

**Comment by icurdinj** [comment]
@Blackskyliner , you are right - if you install a newer version of phpseclib using Composer, the autoloader will pick it up and everything should work.

**Comment by pepijnblom** [comment]
Thanks for the tip, I'll check it out!
