### ISSUE TITLE
check against latest summary of compatibility issues

### ISSUE THREAD

**Issue by hpvd** [Inchoo/Inchoo_PHP7#11]
just a tiny help to bring things together:
this seems to be a good continuously refreshed summary of incompatibilities:
https://magento.stackexchange.com/questions/74008/is-magento-ready-for-php-7/

=> would be good to see all discussed points to be addressed within this extension
and of course one could point from there to this repository...

another compatibility fix is worked on here:
=> https://github.com/MageMechanic/PhpSeven

maybe one can benefit from each-other...

**Comment by icurdinj** [comment]
Good idea. I've checked the thread, and submitted an answer. We have actually fixed all incompatibilities mentioned there.
I've also taken a look at PhpSeven extension. It only fixes one, most obvious incompatibility.

**Comment by hpvd** [comment]
perfect - many thanks for your effort!
