### ISSUE TITLE
cant install any extension

### ISSUE THREAD

**Issue by bonucci** [Inchoo/Inchoo_PHP7#110]
Now that im using the inchoo_php7 i cant installed any extension from magento connect, it gives me a error saying that the extension doesnt support my php version. any advice?

**Comment by renttek** [comment]
The extension in Magento connect all have a package.xml included, which holds some metadata. In this Metadata is also the minimum and maximum version of php, defined by the extension vendor.

The definition looks like this:

```xml
<dependencies>
    <required>
       <php>
           <min>MIN</min>
           <max>MAX</max>
       </php>
   </required>
</dependencies>
```

Most extension I've seen have an maximum version of 6 defined.

One Solution is to use http://freegento.com/ddl-magento-extension.php to download the extension as zipfile and put it "manually" into magento.

I hope this helps a little. If you need further information/help, please let me know.

**Comment by durzel** [comment]
Be warned, if you try and install an extension via Magento Connect and it has a PHP version restriction, the install will fail but the process will also delete the existing version - if you're doing an upgrade.

What I do myself is try and install or upgrade an extension on a development environment, and if it fails I manually go into the download location for the ZIP file `/downloader/.cache/community/`, manually extract it into a temporary directory, edit the package.xml to remove the PHP version restriction (usually just removing the `<max>` directive), and re-archive everything - using e.g. `tar czfpP NEW_ARCHIVE_NAME.tgz .`

I then download that modified archive and re-install it via Magento Connect.

Incidentally I haven't once had any issue with compatibility with any extension that I've installed this way.  It also has the benefit of having the extension still managed by Magento Connect, so you can uninstall it as necessary and be advised of available upgrades, etc.

**Comment by icurdinj** [comment]
The only thing I can add to excellent answers by @renttek and @durzel is that you could contact your extension maker and ask them to make their extensions PHP 7 compatible.
