### ISSUE TITLE
Composer repository

### ISSUE THREAD

**Issue by luckyraul** [Inchoo/Inchoo_PHP7#112]
I've just looking this extension and noticed that you are using firegento repository.

May it is a good idea to migrate to global composer repository(packagist) ?

**Comment by icurdinj** [comment]
The logic here is that, if you are doing Magento 1 over Composer, you will want to use Firegento repository anyhow. What would be the benefit of migrating to packagist?

**Comment by hanhpv** [comment]
I think packagist should be for general PHP libraries only.

**Comment by icurdinj** [comment]
I agree. And Firegento for Magento extensions.

**Comment by luckyraul** [comment]
@icurdinj 

We have a lot of m1 projects with composer and we are not using firegento at all. 
Most of packages are available globally. 

Problems we had when we was using firegento:
1) slow repository update on a release of module. It can be for a week.
2) You can't see downloads statistics
3) You can't remove broken release until it updates
3) dependency for private owned repository vs global repository
4) Any repository included in composer.json overrides global repository so you can have problems with outdated version or outage of firegento.

**Comment by luckyraul** [comment]
@hanhpv M2 Core packages are there

**Comment by luckyraul** [comment]
@icurdinj If you add this project to packagist - it won't break firegento users.
