### ISSUE TITLE
Magento Installation with 7.0 w/o ext-mcrypt installed

### ISSUE THREAD

**Issue by Blackskyliner** [Inchoo/Inchoo_PHP7#114]
I just wanted to note that if there is no mcrypt extension installed and you use the mcrypt polyfill you will need to patch `app/code/core/Mage/Install/etc/install.xml` and remove mcrypt from the checked extensions. otherwise you won't get past the language configuration. It will then, if the polyfill is installed, install w/o problems.

I don't know if we want to write this down somewhere for interested ppls. which want to initially install Magento in a PHP7 environment.

In Theory we could also provide a Composer-Hook, check the stuff above and do the patching of the install.xml if we detect no mcrypt extension, but the polyfill exists.

**Comment by icurdinj** [comment]
Your note added to wiki.
