### ISSUE TITLE
Update Wiki ProperInstallation

### ISSUE THREAD

**Issue by EmPeWe** [Inchoo/Inchoo_PHP7#116]
> Use n98-magerun.phar dev:module:list to verify that Inchoo_PHP7 is on the list. If it is not try to add it: n98-magerun.phar dev:module:enable Inchoo_PHP7.

Instead of force to enable the module, you should try to clean/flush cache first:
`$ n98-magerun.phar cache:clean && n98-magerun.phar cache:flush`

**Comment by icurdinj** [comment]
Wiki updated. I think you could have made a pull request on wiki instead of issue?
