### ISSUE TITLE
because of mature process: check compatibility to latest php 7.0

### ISSUE THREAD

**Issue by hpvd** [Inchoo/Inchoo_PHP7#12]
Since PHP 7 is still maturing, it may be a good idea to check compatibility to latest available version of PHP 7 from time to time...
(this time 7.0.1 see http://www.php.net/ChangeLog-7.php)

**Comment by durzel** [comment]
7.0.1 is a minor release so is unlikely to introduce any new incompatibilities, but you're right that it's good to keep an eye on this stuff.

**Comment by icurdinj** [comment]
What @durzel said. If anything, we expect 7.0.* to be more compatible (less buggy) with point releases. Further compatibility breaks are to be expected from 7.1, and we will have an eye on it.
