### ISSUE TITLE
Something else to override

### ISSUE THREAD

**Issue by hhdivil** [Inchoo/Inchoo_PHP7#120]
`Fatal error: Uncaught Error: Function name must be a string in /var/www/vhosts/dev.onestophire.com/htdocs/app/code/core/Mage/Core/Model/Layout.php:555`

`$out .= $this->getBlock($callback[0])->$callback[1]();`

doesn't work on PHP7, should be this:

`$out .= $this->getBlock($callback[0])->{$callback[1]}();`

**Comment by icurdinj** [comment]
If I had a dime every time people didn't bother to see closed issues, but did bother to create a new one...

**Comment by salubrium** [comment]
Why not just make 1.9.2.4 the master branch? The current master seems like it's not useable for anything as it's just the helper. I think that's where a lot of the issues are coming from. I'd used this repo quite a lot and never had problems grabbing master and then later it stopped working and I had to go looking to see why. My 2c
