### ISSUE TITLE
Fatal error: Uncaught Error: Class 'Inchoo_PHP7_Helper_Data' not found

### ISSUE THREAD

**Issue by JuanjoR** [Inchoo/Inchoo_PHP7#122]
I downloaded the module twice and I installed the module several times in my site and always the same result

After installing, when I clear the cache it gives me error

`Fatal error: Uncaught Error: Class 'Inchoo_PHP7_Helper_Data' not found in /var/www/vhosts/disfresses.cat/httpdocs/app/Mage.php:547 Stack trace: #0 /var/www/vhosts/disfresses.cat/httpdocs/includes/src/Mage_Core_Model_Resource_Setup.php(308): Mage::helper('core') #1 /var/www/vhosts/disfresses.cat/httpdocs/includes/src/Mage_Core_Model_Resource_Setup.php(235): Mage_Core_Model_Resource_Setup->applyUpdates() #2 /var/www/vhosts/disfresses.cat/httpdocs/includes/src/__default.php(21355): Mage_Core_Model_Resource_Setup::applyAllUpdates() #3 /var/www/vhosts/disfresses.cat/httpdocs/includes/src/__default.php(21281): Mage_Core_Model_App->_initModules() #4 /var/www/vhosts/disfresses.cat/httpdocs/app/Mage.php(683): Mage_Core_Model_App->run(Array) #5 /var/www/vhosts/disfresses.cat/httpdocs/index.php(83): Mage::run('', 'store') #6 {main} thrown in /var/www/vhosts/disfresses.cat/httpdocs/app/Mage.php on line 547`

I have Inchoo_PHP7 2.1.1. in magento 1.9.3.4 and PHP 7.0.16 with the modified .htaccess `<IfModule mod_php7.c>`

Test result: inchoo_php7_test.php
`Running tests...
- 1: CLI version of PHP is Ok: 7.0.16 (Note that CLI and web server versions of PHP may differ.)
- 2: Inchoo_PHP7 module is enabled.
- 3: Inchoo_PHP7 version is: 2.1.1, Magento core version is: Community 1.9.3.4 - Ok.
- 4: Magento Connect Packager is overridden.
- 5: Magento Session Resource is overridden.
Tests successful: 5/5.`

The problem is that the scaners also indicate that I have malware on the site when I upload the module

[https://sitecheck.sucuri.net/ whit malware](http://prntscr.com/g4nsp2)

And disappears after removing the module

[https://sitecheck.sucuri.net/ after removing](http://prntscr.com/g4nvqj)

In any case I want to say that the module is infected, I have it installed in other sites and it works correctly, but I do not understand why it gives that error and also indicates that the site is infected

I have seen that in [http://inchoo.net/magento/its-alive/#comment-434195](http://inchoo.net/magento/its-alive/#comment-434195) also happens the same error to some participants of the comments in other versions of magento, so I am not alone, someone else has happened this?

**Comment by jonbunce** [comment]
Exactly the same problem, although mine is referring to smartwave_all as the plugin so i believe my issue may be related to the porto theme. I havent time to debug at the moment but the recommended grep search for incompatible plugins didnt find anything...

**Comment by ivanweiler** [comment]
I'm not sure why autoload can't find mentioned class ?! Did you managed to figure out what the problem is/was?

Btw, it's funny that scanner is triggered by not found error :)

**Comment by jm111015** [comment]
Hi,
Facing the same issue here:

Fatal error: Uncaught Error: Class 'Inchoo_PHP7_Helper_Data' not found 

Are there any fixes on this?

Thank you,
JM

**Comment by udovicic** [comment]
Module has been deprecated in favor of official Magento patch, you should not be using it.

**Comment by jm111015** [comment]
Thank you. So what I will be using sir? My PHP  version is 7 so I assume that said module can help me to support my Magento site.

**Comment by jm111015** [comment]
@udovicic my  Magento ver. 1.9.2.1 and I want it to support with PHP 7 sir.  But got this Fatal error: Uncaught Error: Class 'Inchoo_PHP7_Helper_Data' after installed Inchoo_PHP7.

Thanks.
