### ISSUE TITLE
Syntax error during running shell/inchoo_php7_test.php 

### ISSUE THREAD

**Issue by julianmurillo** [Inchoo/Inchoo_PHP7#128]
PHP Parse error:  syntax error, unexpected ':', expecting ';' or '{' in /data/web/dev01/shell/inchoo_php7_test.php on line 28

PHP 5.6.30-12 (cli)

Anyone?

**Comment by durzel** [comment]
Return type declarations is a new feature in PHP 7.  You're attempting to use this module on a PHP version less than 7.0.  You do not need this module with PHP versions below 7.0.

**Comment by julianmurillo** [comment]
I am trying to install Inchoo PHP7 in a Magento 1 webshop with PHP 5.6; What should I use then?

**Comment by durzel** [comment]
You don't need to install Inchoo_PHP7 if you're not using PHP 7.

The purpose of this module is to make Magento 1 work with PHP 7.  If you're using PHP 5.6.30-12, you don't need to use this module at all, and in fact should not install it.

**Comment by julianmurillo** [comment]
The webshop will be updated soon to php7 ;) so that's why i am installing the module

**Comment by durzel** [comment]
Ok :)  Well, you'll need to install PHP 7 _before_ you activate this module.

**Comment by franzludilabel** [comment]
durzel, your kindness is limitless :)

**Comment by ivanweiler** [comment]
I even think module is working on php 5, but the test isn't :) Anyway, closing the issue.
