### ISSUE TITLE
Running on PHP 7.1 page

### ISSUE THREAD

**Issue by tdgroot** [Inchoo/Inchoo_PHP7#137]
The RunningOnPHP7.1 wiki page is becoming a bit awkward, because [PHP 7.0 support will end on 3 Dec 2018](http://php.net/supported-versions.php). But I figure you already know, since there's some nice progress going on in the `develop` branch.

IMO, the RunningOnPHP7.1 wiki page should be deleted.

**Comment by ivanweiler** [comment]
https://github.com/Inchoo/Inchoo_PHP7/wiki/PHP-7.1-and-7.2

**Comment by tdgroot** [comment]
Great stuff, thank you :).
