### ISSUE TITLE
error 

### ISSUE THREAD

**Issue by Nikhilthehokage** [Inchoo/Inchoo_PHP7#154]
<?php
  include('dbcon.php');
 
  if(isset($_POST("login")))
  {
	  $username = $_POST('username');
	  $password = $_POST('password');
	  
	  $qry= "SELECT * FROM `admin` WHERE 'username'='$username'AND 'password'=$password';";
	  $run= mysqli_query($con,$qry);
	  $row=mysqli_num_rows($run);
	  
	  if($row < 1)
	  {
		  ?>
		  <script>
		    alert('Username or password  may be incorrect')	;
            window.open('login.php','_self');			
		  </script>
		  <?php
	  }
	  else
	  {
		  $data= mysqli_fetch_assoc($run);
		  $id= $data['ID'];
		  echo " ID = ".$id;
	  }
  }
?>

for this code 
output is
( ! ) Fatal error: Cannot use isset() on the result of an expression (you can use "null !== expression" instead) in C:\wamp64\www\SMS\login.php on line 35
please help

**Comment by udovicic** [comment]
Hi @Nikhilthehokage ,

Please note that this extension is deprecated and should not be used. As per [README.md](https://github.com/Inchoo/Inchoo_PHP7/blob/master/README.md) you can read more info [here](https://inchoo.net/magento/magento-1-official-php-7-2-patches/).
