### ISSUE TITLE
compatibility to Magento 1.9.2.3

### ISSUE THREAD

**Issue by hpvd** [Inchoo/Inchoo_PHP7#16]
Please document every experience regarding compatibility to latest magento CE 1.9.2.3

**Comment by durzel** [comment]
Installed 1.9.2.3 a couple of days ago, no issues at all with PHP 7.0.2 that aren't fixed by this module.

**Comment by icurdinj** [comment]
Same here - no issues with 1.9.2.3 (and none were expected, frankly).
