### ISSUE TITLE
.htaccess <IfModule> issue

### ISSUE THREAD

**Issue by durzel** [Inchoo/Inchoo_PHP7#18]
Minor thing this, only noticed it today.  The .htaccess that ships with Magento 1.x includes a set of PHP settings that will be ignored by an install running PHP 7.x.

This is because they are contained within an `<IfModule mod_php5.c>` declaration.

The simple fix for this is to change it to `<IfModule mod_php7.c>`.  Assuming no other incompatible changes have been made to the content of this block, there are no issues.

This is fairly important because one of the things added in this block by default is: 

```
php_value memory_limit 256M
php_value max_execution_time 18000
```
..which will be ignored without this change.

Do you think this is important enough to be included in this modul

**Comment by icurdinj** [comment]
This is true, and quite important on setups which use mod_php. Most production sites don't, but many development localhosts do. I don't think we can "patch" .htaccess from the module itself, but we document this in readme file, just to remind users.

**Comment by durzel** [comment]
Cool, that would seem to be sufficient :+1:
