### ISSUE TITLE
May be incompatible Enterprise TargetRule

### ISSUE THREAD

**Issue by artmouse** [Inchoo/Inchoo_PHP7#24]
`grep -rnPe '->\$.+\[.+\]\(.*\)' app/`
`app/code/core/Mage/Core/Model/Layout.php:555:                $out .= $this->getBlock($callback[0])->$callback[1]();
app/code/core/Mage/ImportExport/Model/Export/Entity/Product/Type/Abstract.php:99:                $data['filter_options'] = $this->$data['options_method']();
app/code/core/Mage/ImportExport/Model/Export/Entity/Customer.php:250:                    $data['filter_options'] = $this->$data['options_method']();
app/code/core/Mage/ImportExport/Model/Import/Uploader.php:135:                $params['object']->$params['method']($filePath);
app/code/core/Enterprise/TargetRule/Model/Resource/Index.php:315:                        $v = $this->$callback[0]($v, $callback[1]);
`

**Comment by benjamw** [comment]
See #21 and #22

**Comment by benjamw** [comment]
#21 and #22 have been closed, see their replacements #26 and #27

**Comment by icurdinj** [comment]
Pull requests #26 & #27 merged to appropriate branches.
