### ISSUE TITLE
ERR (3):  exception 'Zend_Exception' with message 'dbModel read resource does not implement Zend_Db_Adapter_Abstract'

### ISSUE THREAD

**Issue by yspatel** [Inchoo/Inchoo_PHP7#25]
2016-03-10T19:27:14+00:00 ERR (3): 
exception 'Zend_Exception' with message 'dbModel read resource does not implement Zend_Db_Adapter_Abstract' in /lib/Varien/Data/Collection/Db.php:187
Stack trace:
#0 /app/code/core/Mage/Core/Model/Resource/Db/Collection/Abstract.php(134): Varien_Data_Collection_Db->setConnection(false)
#1 /app/code/local/Mage/Core/Model/Config.php(1351): Mage_Core_Model_Resource_Db_Collection_Abstract->__construct(Array)
#2 /app/code/local/Mage/Core/Model/Config.php(1383): Mage_Core_Model_Config->getModelInstance('wordpress_resou...', Array)
#3 /app/Mage.php(491): Mage_Core_Model_Config->getResourceModelInstance('wordpress/post_...', Array)
#4 /app/code/community/Fishpig/Wordpress/Block/Sidebar/Widget/Posts.php(75): Mage::getResourceModel('wordpress/post_...')
#5 /app/code/community/Fishpig/Wordpress/Block/Sidebar/Widget/Posts.php(36): Fishpig_Wordpress_Block_Sidebar_Widget_Posts->_getPostCollection()
#6 /app/code/core/Mage/Core/Block/Abstract.php(918): Fishpig_Wordpress_Block_Sidebar_Widget_Posts->_beforeToHtml()
#7 /app/code/core/Mage/Core/Model/Email/Template/Filter.php(208): Mage_Core_Block_Abstract->toHtml()
#8 [internal function]: Mage_Core_Model_Email_Template_Filter->blockDirective(Array)
#9 /lib/Varien/Filter/Template.php(163): call_user_func(Array, Array)
#10 /app/code/core/Mage/Core/Model/Email/Template/Filter.php(560): Varien_Filter_Template->filter('<h2 class="filt...')
#11 /app/code/core/Mage/Cms/Block/Page.php(101): Mage_Core_Model_Email_Template_Filter->filter('<h2 class="filt...')
#12 /app/code/core/Mage/Core/Block/Abstract.php(919): Mage_Cms_Block_Page->_toHtml()
#13 /app/code/core/Mage/Core/Block/Abstract.php(637): Mage_Core_Block_Abstract->toHtml()
#14 /app/code/core/Mage/Core/Block/Abstract.php(577): Mage_Core_Block_Abstract->_getChildHtml('cms_page', true)
#15 /app/code/core/Mage/Page/Block/Html/Wrapper.php(52): Mage_Core_Block_Abstract->getChildHtml('', true, true)
#16 /app/code/core/Mage/Core/Block/Abstract.php(919): Mage_Page_Block_Html_Wrapper->_toHtml()
#17 /app/code/core/Mage/Core/Block/Text/List.php(43): Mage_Core_Block_Abstract->toHtml()
#18 /app/code/core/Mage/Core/Block/Abstract.php(919): Mage_Core_Block_Text_List->_toHtml()
#19 /app/code/core/Mage/Core/Block/Abstract.php(637): Mage_Core_Block_Abstract->toHtml()
#20 /app/code/core/Mage/Core/Block/Abstract.php(581): Mage_Core_Block_Abstract->_getChildHtml('content', true)
#21 /app/design/frontend/smartwave/porto/template/page/1column.phtml(59): Mage_Core_Block_Abstract->getChildHtml('content')
#22 /app/code/core/Mage/Core/Block/Template.php(241): include('/XXX')
#23 /app/code/core/Mage/Core/Block/Template.php(272): Mage_Core_Block_Template->fetchView('frontend/XXX...')
#24 /app/code/core/Mage/Core/Block/Template.php(286): Mage_Core_Block_Template->renderView()
#25 /app/code/core/Mage/Core/Block/Abstract.php(919): Mage_Core_Block_Template->_toHtml()
#26 /app/code/local/Mage/Core/Model/Layout.php(557): Mage_Core_Block_Abstract->toHtml()
#27 /app/code/core/Mage/Core/Controller/Varien/Action.php(390): Mage_Core_Model_Layout->getOutput()
#28 /app/code/core/Mage/Cms/Helper/Page.php(137): Mage_Core_Controller_Varien_Action->renderLayout()
#29 /app/code/core/Mage/Cms/Helper/Page.php(52): Mage_Cms_Helper_Page->_renderPage(Object(Mage_Cms_IndexController), 'XXX')
#30 /app/code/core/Mage/Cms/controllers/IndexController.php(45): Mage_Cms_Helper_Page->renderPage(Object(Mage_Cms_IndexController), 'XXX')
#31 /app/code/core/Mage/Core/Controller/Varien/Action.php(418): Mage_Cms_IndexController->indexAction()
#32 /app/code/core/Mage/Core/Controller/Varien/Router/Standard.php(254): Mage_Core_Controller_Varien_Action->dispatch('index')
#33 /app/code/core/Mage/Core/Controller/Varien/Front.php(172): Mage_Core_Controller_Varien_Router_Standard->match(Object(Mage_Core_Controller_Request_Http))
#34 /app/code/core/Mage/Core/Model/App.php(365): Mage_Core_Controller_Varien_Front->dispatch()
#35 /app/Mage.php(684): Mage_Core_Model_App->run(Array)
#36 /index.php(84): Mage::run('...', 'store')

**Comment by icurdinj** [comment]
That's not an issue report.
