### ISSUE TITLE
One-Step-Checkout

### ISSUE THREAD

**Issue by Insect2015** [Inchoo/Inchoo_PHP7#28]
hello Support,

I see that my one-step-checkout page is not working after I have update to PHP7 and install Inchoo.

Could someone help me?

Best regards,
Michel

**Comment by ivanweiler** [comment]
Hello @Insect2015, 

OneStepCheckout is Magento commercial plugin, did you try contacting their support through official page, they should have a solution? http://www.onestepcheckout.com/support/

**Comment by Insect2015** [comment]
Hello invanweiler,

I use the One-step-checkout from http://www.magestore.com/magento-one-step-checkout-extension.html/ But I have send a email!

**Comment by icurdinj** [comment]
We hope Magestore will help you with that.
