### ISSUE TITLE
Firegento doesn't update with new releases

### ISSUE THREAD

**Issue by icurdinj** [Inchoo/Inchoo_PHP7#35]
Don't know why, have to investigate... If anyone has more experience with Firegento and an idea why this happens, help is always welcome.

**Comment by t-richards** [comment]
@icurdinj The Firegento repository is a [Satis](https://github.com/composer/satis) repository. As such, it  follows the rules outlined here: https://getcomposer.org/doc/02-libraries.md#tags with regard to picking up on valid version numbers.

The current tag naming scheme for this project, `CE-X.Y.Z` or `EE-X.Y.Z` -- these do not match any of the formats outlined in the documentation. A more appropriate tag naming scheme for composer compatibility might be something like `X.Y.Z-CE` or `X.Y.Z-EE`.

You might also consider splitting this project into separate repos or branches to distinguish between the CE/EE versions of the module. This would eliminate the need for tag prefixes/suffixes.

**Comment by t-richards** [comment]
@icurdinj I just tried to pull in your `1.0.3-CE` tag into my private satis repo, but it didn't show up in the releases section. Additionally, I created a test repo and tried a few variations of tags which included `CE` in them, and none of them counted as "releases" in the eyes of Satis/Composer.

If you want releases to show up in a satis repository, it looks like you must be very conservative in your tag naming. Any git tag prefix/suffix beyond what is explicitly listed in the documentation will result in the tag not counting as a "release".

IMO, the best way to proceed from here is the split repo approach. One repo for the CE version, and one repo for the EE version.
In the split-repo layout, a Magento CE user might specify in their composer.json:
```json
"require": {
  "inchoo/php7-ce": "^1.0.4"
}
```

Whereas the Magento EE user would do this:
```json
"require": {
  "inchoo/php7-ee": "^1.0.4"
}
```

**Comment by icurdinj** [comment]
Thank you very much @t-richards for all the information and effort. Since the difference between CE and EE versions is very small, and it is very convenient to keep everything in one repository and just 2 branches, I finally decided to make a simple "1.0.3" release of master branch, which is for CE and should show up on Firegento. EE version will just have to be installed from "dev-EE" version/branch, at least for the time being. 
At least it's better for CE users, while being the same as it was for EE users and contributing developers, so I guess it's some small progress after all.

**Comment by t-richards** [comment]
The `1.0.3` tag looks good to me. It shouldn't be too much longer before it appears on the Firegento repo.
