### ISSUE TITLE
Image Upload

### ISSUE THREAD

**Issue by gammyduck** [Inchoo/Inchoo_PHP7#36]
Preview:
https://i.gyazo.com/2e5b73747f751ba459d9fa4a8835a6ce.png

Problem And Solution:
http://magento.stackexchange.com/questions/93066/magento-1-9-2-and-php7-image-upload-error

**Comment by durzel** [comment]
This (and other Uniform Variable Syntax issues in Magento 1.x) are already resolved by this module.

**Comment by gammyduck** [comment]
As of when? Is there a reason I am missing this fix as I've only installed inchoo recently

**Comment by durzel** [comment]
Without knowing your exact configuration I'd hazard a guess that this error you're getting related to the permissions changes that SUPEE-7405 added (and 1.9.2.4 later resolved):

https://community.magento.com/t5/Security-Patches/after-installing-SUPEE-7405-can-no-longer-add-or-change-images/td-p/26785

I don't think this error relates to PHP 7 personally, as this module fixed it in one of the earliest releases.

**Comment by gammyduck** [comment]
The solution above resolved my issue. Maybe I need to check my inchoo installation

**Comment by durzel** [comment]
Yeah, you probably need to make sure it's installed properly.

6edf619cea94b4f4344587112c930d4df0b7cd2e resolved this issue (in the same way), and was committed 4 months ago.

**Comment by gammyduck** [comment]
Thanks for the quick responses anyway!

**Comment by icurdinj** [comment]
And big thanks to @durzel for such a great community effort!
