### ISSUE TITLE
Any suggestions for PHP Fatal error: Uncaught Error: Function name must be a string...

### ISSUE THREAD

**Issue by WesMage** [Inchoo/Inchoo_PHP7#40]
Hello
I'm getting this error when I upgrade to PHP7.
I've installed the inchoo_PHP7  module and updated .htaccess with mod_php settings as per the readme,
If anyone has any suggestions it would be much appreciated. 
Thanks in advance 

PHP Fatal error: Uncaught Error: Function name must be a string in /var/www/html/mydomain.com/app/code/core/Mage/Core/Model/Layout.php:555\nStack trace:\n#0 /var/www/html/mydomain.com/app/code/core/Mage/Core/Controller/Varien/Action.php(390): Mage_Core_Model_Layout->getOutput()\n#1 /var/www/html/mydomain.com/app/code/core/Mage/Cms/Helper/Page.php(137): Mage_Core_Controller_Varien_Action->renderLayout()\n#2 /var/www/html/mydomain.com/app/code/core/Mage/Cms/Helper/Page.php(52): Mage_Cms_Helper_Page->_renderPage(Object(Mage_Cms_IndexController), 'home')\n#3 /var/www/html/mydomain.com/app/code/core/Mage/Cms/controllers/IndexController.php(45): Mage_Cms_Helper_Page->renderPage(Object(Mage_Cms_IndexController), 'home')\n#4 /var/www/html/mydomain.com/app/code/core/Mage/Core/Controller/Varien/Action.php(418): Mage_Cms_IndexController->indexAction()\n#5 /var/www/html/mydomain.com/app/code/core/Mage/Core/Controller/Varien/Router/Standard.php(254): Mage_Core_Controller_Varien_Action->dispatch('index')\n#6 /var/www/html/mydomain.com/app/code/cor in /var/www/html/mydomain.com/app/code/core/Mage/Core/Model/Layout.php on line 555

**Comment by schmite** [comment]
The module fixes this incompatibility with php 7.
You cleared the cache?

**Comment by WesMage** [comment]
@schmite thanks for the quick response. 
I certainly have cleared all the individual magento caches eg blocks_html etc however not the big buttons on the cache page in magento admin. 
I also didn't cheap opCache
I actually have had the module installed for approximately 1 month prior to upgrading to PHP 7 so I would have expected that any cache would have expired too. 
Would you recommend flushing every cache in every way or even using command line to flush cache? If so if you could share the command that would be very helpful and which dir I run it from as I'm only just leaving. 
Also perhaps I should install the module again just in case something happened with some of the files? 
Any other suggestions are very welcome 
Thank you

**Comment by WesMage** [comment]
Excuse my autocorrections causing typos. 
I didn't  clear opcache 
I'm just learning with command line

**Comment by schmite** [comment]
Which method you use to install the extension?
This error has appeared to me in stores that are running on php7 without the extension enabled.

**Comment by WesMage** [comment]
I copied the extension into the magneto root folder via Filezilla sftp

Which method you use to install the extension?
This error has appeared to me in stores that are running on php7 without
the extension enabled.

—
You are receiving this because you authored the thread.
Reply to this email directly or view it on GitHub
<https://github.com/Inchoo/Inchoo_PHP7/issues/40#issuecomment-217588267>

**Comment by icurdinj** [comment]
@WesMage , have you managed to solve this problem? It did look like the extension was not properly installed.

**Comment by WesMage** [comment]
@icurdinj I haven't had time to try again. Do you mind if we leave the issue  open a little longer in case I have some more questions?

**Comment by WesMage** [comment]
Hi @schmite & @icurdinj 
Unfortunately I'm receiving the same error after performing the following steps:
1) download zip version of this extension from github
2) unzip
3) Using filezilla, Drag app folder to magento root
4) Select all magento cache and hit refresh
5) Click "Flush magento cache" button 
6) log out and login to magento admin

My sysadmin then upgraded to php7 and received the same error. 
I've since reverted down to 5.6. 

If anyone has any suggestions or you are interested in some paid freelance work to take a look please let me know. 
Many thanks 
Wes

**Comment by cjwijtmans** [comment]
https://www.atwix.com/magento/magento-and-php-7/

**Comment by icurdinj** [comment]
As already answered by others, this module fixes that incompatibility. It's difficult to say what exactly happens on @WesMage's setup, but, if someone is interested in contacting him directly and getting paid to help, I guess everyone here would like to know what it was once its fixed.

**Comment by mblarsen** [comment]
When you get this error it is because the module is not picked up by Magento.

Ensure that the files are in place either by adding the manually or using modman. You can use `modman repair` to verify that files and dirs are linked correctly. 

If using modman ensure symlinks are enabled.

Ensure that the webuser has rights to read all files (also the ones in the modman modules dir if you have one). *THIS WAS THE PROBLEM FOR ME* 

Use `n98-magerun.phar dev:module:list` to verify that `Inchoo_PHP7` is on the list. If it is not try to add it: `n98-magerun.phar dev:module:enable Inchoo_PHP7`.

Use `n98-magerun.phar dev:module:rewrite:conflicts` to ensure that this module isn't conflicting with other modules you've installed.

If not check that rewrites are also registered `n98-magerun.phar dev:module:rewrite:list`:

```
| helpers        | core/data                                                        | Inchoo_PHP7_Helper_Data                                                                                                                        |
| models         | core/layout                                                      | Inchoo_PHP7_Model_Layout                                                                                                                       |
| models         | importexport/import_uploader                                     | Inchoo_PHP7_Model_Import_Uploader                                                                                                              |
| models         | importexport/export_entity_product_type_configurable             | Inchoo_PHP7_Model_Export_Entity_Product_Type_Configurable                                                                                      |
| models         | importexport/export_entity_product_type_grouped                  | Inchoo_PHP7_Model_Export_Entity_Product_Type_Grouped                                                                                           |
| models         | importexport/export_entity_product_type_simple                   | Inchoo_PHP7_Model_Export_Entity_Product_Type_Simple                                                                                            |
| models         | importexport/export_entity_customer                              | Inchoo_PHP7_Model_Export_Entity_Customer                                                                                                       |
| models         | catalog/product_link_api_v2                                      | Inchoo_PHP7_Model_Product_Link_Api_V2                                                                                                          |
```
