### ISSUE TITLE
Tags are a mess

### ISSUE THREAD

**Issue by peterjaap** [Inchoo/Inchoo_PHP7#42]
Hi,

The tags are a mess. There now is a 1.0.3 and a 1.0.3-CE tag, as well as other versionings.

Could you remove all non-semver tags? I think 1.0.3 is the most recent correct one.

When I add ^1.0.0 to my composer.json, it'll now fetch '1.0.3', which is correct. But 1.0.3-CE doesn't make sense.

**Comment by icurdinj** [comment]
Yes, you are right. Non-semver releases deleted (to extent that GitHub allows)...
