### ISSUE TITLE
Overriding the downloader/lib/Mage/Connect/Packager.php file

### ISSUE THREAD

**Issue by benjamw** [Inchoo/Inchoo_PHP7#43]
Not an issue per se, but rather a note on how to override the `downloader/lib/Mage/Connect/Packager.php` file to make it PHP7 compliant:

http://magento.stackexchange.com/questions/32101/extend-magento-downloader/48540#answer-115425

I haven't had need of this, since I don't use the downloader, but other people might find this useful.

**Comment by icurdinj** [comment]
Maybe we should start the wiki, and collect such pieces of knowledge that don't necessarilly belong to extension code there?

**Comment by icurdinj** [comment]
Made a Wiki for extension, included this information there.
