### ISSUE TITLE
Incorrect rewrite for Enterprise_TargetRule_Model_Resource_Index

### ISSUE THREAD

**Issue by Persata** [Inchoo/Inchoo_PHP7#44]
Hi all,

We're about to migrate our store to PHP7 and I've been testing it with the Inchoo patch installed (great job btw!), and noticed this in the system.log file:

```
ERR (3): Notice: Array to string conversion  in /{server_path}/app/code/core/Enterprise/TargetRule/Model/Resource/Index.php on line 315
ERR (3): Notice: Undefined property: Enterprise_TargetRule_Model_Resource_Index::$Array  in /{server_path}/app/code/core/Enterprise/TargetRule/Model/Resource/Index.php on line 315
```

which is supposed to be fixed by rewriting the above class to Inchoo_PHP7_Model_Resource_Index.

After using Xdebug to dig into it, it seems that the rewrite XML specified in this module's config.xml is incorrect, and the resource model class Enterprise_TargetRule_Model_Resource_Index is still being instantiated.

I believe the rewrite should actually be:

```
<enterprise_targetrule_resource>
    <rewrite>
        <index>Inchoo_PHP7_Model_Resource_Index</index>
    </rewrite>
</enterprise_targetrule_resource>
```

I've tested this change and it loads Inchoo_PHP7_Model_Resource_Index correctly, which fixes the issue. I'll also file a pull request with a fix.

Thanks!

**Comment by icurdinj** [comment]
Pull request merged, thanks.
