### ISSUE TITLE
Incorrect sorting in the calculation of the discount

### ISSUE THREAD

**Issue by icurdinj** [Inchoo/Inchoo_PHP7#5]
A user reported: "This strange behavior is due to a change in the work function uasort. I described it in detail on the SO: http://stackoverflow.com/questions/34281113/the-different-behavior-of-the-function-uasort-in-php-5-5-and-php-7-0"
Be warned until I get around to checking & fixing this.
If someone fixes this before, pull requests are welcome.

**Comment by icurdinj** [comment]
Fix merged from pull request, awaiting testing results.

**Comment by ed29** [comment]
This works for php7:https://github.com/facebook/hhvm/issues/2416

**Comment by icurdinj** [comment]
Seems fixed.
