### ISSUE TITLE
PHP7 - Syntax error Unexpected Token 

### ISSUE THREAD

**Issue by thomasthaulow** [Inchoo/Inchoo_PHP7#51]
Hello, 

I dont know if I can ask this question here, so just tell if I should delete. 

After upgrading to php7, I have started getting javascript errors as: 
Uncaught SyntaxError: Unexpected token < in JSON at position 0 
and 
Uncaught SyntaxError: Unexpected token }

Affected onestepcheckouts buttons on page and my "add review" in magneto. 

Anyone had issues like this, any changes in php7 I should know of? 

Thank you in advance,

**Comment by icurdinj** [comment]
One step checkout? Is it provided by a 3rd party extension?

**Comment by mrlerch** [comment]
Try to contact Magestore. They are pretty good when it comes to their extensions. Or try updating it to the latest version.

Martin

**Comment by udovicic** [comment]
I have tested this extension with PHP 7.0.8 and everything seems to be working as expected. Can you give aus any more info?

**Comment by Mic2005** [comment]
There are several onestepcheckouts but I run OneStepCheckout (.com), CE 1.9.2.4 and PHP7, no problems here.

**Comment by icurdinj** [comment]
I guess this was one more extension incompatibility. We get a lot of those, but can't do much about them.
