### ISSUE TITLE
API: Argument product should be productId

### ISSUE THREAD

**Issue by Mic2005** [Inchoo/Inchoo_PHP7#52]
We encouter some problems with the Magento API after we switched from Magento CE 1.7.0.2 (HHVM) to CE 1.9.2.4 (PHP7 and this extension) with argument 'product'.
The problem is in the argument 'product', it should be 'productId'. When we replace 'product' with 'productId' in the request, it returns the correct result.
I can't believe that this argument has changed in Magento. Is it?
I see a overwrite class catalog/product_link_api_v2.
Can you help me debug and fix this?

**Comment by Mic2005** [comment]
Inchoo, is this a bug?

**Comment by ivanweiler** [comment]
I'm not sure if Magento changed anything there (it doesn't seem so), but overwritten class has the same input as original one so it doesn't seem related to PHP7 module ?!

Can you maybe temporarily disable rewrite in module and patch original Magento class 
app/code/core/Mage/Catalog/Model/Product/Link/Api/V2.php

Replace: $data->$attribute['code'] 
With: $data->{$attribute['code']}

(it's what rewrite is patching )

If it's the same productId behavior as with rewrite, then Magento changed something.

**Comment by Mic2005** [comment]
I did not find any change in the Magento API >1.9 but I found this rewrite class that's why i ask you the question. The developer found that it was not related to PHP7 because they encounter it also on a clean 1.9.2 @PHP5.4 so it's not your extension. I will try to test your hack to find out if it solve the problem but i think not. I will close this issue for now. Thanks for your advice.
