### ISSUE TITLE
Decoding failed: Syntax error

### ISSUE THREAD

**Issue by aminfri** [Inchoo/Inchoo_PHP7#53]
Hi all, 
This error comes up when trying to save attributes. I know at some point two fixes where suggested and merged but i still get this error when trying to modify and then save my attributes. any suggestions?

**Comment by aminfri** [comment]
turn out to be a compatibility issue with a go mage plugin. sorted.

**Comment by rtjc** [comment]
Hi, 

we have the same problem. How did you solve it?

**Comment by aminfri** [comment]
@rtjc 
search for jsonDecode and make sure its not getting null inputs, follow this:
https://github.com/Inchoo/Inchoo_PHP7/pull/31/files
