### ISSUE TITLE
Getting 500 Error on Magento 1.9.2.3 running PHP 7.0.9 + Nginx 1.11

### ISSUE THREAD

**Issue by ndianabasi** [Inchoo/Inchoo_PHP7#57]
Hello,

I installed this extension on Magento 1.9.2.3 running on PHP 7.0.9 + Nginx 1.11 but I'm getting 500 errors everywhere.

Any idea where the problem is?

Thank you.

**Comment by icurdinj** [comment]
Try wiki first: https://github.com/Inchoo/Inchoo_PHP7/wiki
