### ISSUE TITLE
Typo in Session.php?

### ISSUE THREAD

**Issue by hgpit** [Inchoo/Inchoo_PHP7#62]
Hello,

I am a noob at coding etc, but in the Session.php file contained in the fix pack, on line 40:
`const SEESION_MAX_COOKIE_LIFETIME = 3155692600;`

Is "SEESION_MAX_COOKIE_LIFETIME" spelt incorrectly on purpose, or is this a bug?

Thank you!

**Comment by hgpit** [comment]
Okay, I also noticed that it's spelt the same way on lines 120 and 121. This seems weird though?

**Comment by hostep** [comment]
Don't worry, it's one of the many many typo's in Magento's core code ;)
https://github.com/OpenMage/magento-mirror/blob/1.9.2.4/app/code/core/Mage/Core/Model/Resource/Session.php#L40

**Comment by icurdinj** [comment]
They could easily fix the typos with a search/replace in core, but then, all extensions which use that parts would break...
So, I guess, Magento core typos will haunt us forever :smile:
