### ISSUE TITLE
Can't view orders in back-end

### ISSUE THREAD

**Issue by hgpit** [Inchoo/Inchoo_PHP7#66]
Magento EE v1.14.2.4, PHP 7

Hi we have the PHP7 Inchoo extension installed, and when we click to view a customer's orders in the back-end we get the following error.

We have contacted Magento support, but because the error references 'Inchoo_PHP7_Model_Layout', they are just telling us to uninstall the plugin and downgrade to PHP5.6 :-/

Can anyone offer any advice or a possible fix?

Thank you!

"
SQLSTATE[42S22]: Column not found: 1054 Unknown column 'main_table.entity_id' in 'field list', query was: SELECT COUNT(*) FROM (SELECT `main_table`.`entity_id`, `main_table`.`increment_id`, `main_table`.`customer_id`, `main_table`.`created_at`, `main_table`.`grand_total`, `main_table`.`order_currency_code`, `main_table`.`store_id`, `main_table`.`billing_name`, `main_table`.`shipping_name`, `shell_request`.* FROM (SELECT `main_table`.*, GROUP_CONCAT(`name` SEPARATOR '\n') AS `name` FROM `sales_flat_order_grid` AS `main_table`
 LEFT JOIN `sales_flat_order_item` AS `order_item` ON order_item.order_id = main_table.entity_id WHERE (order_item.`parent_item_id` IS NULL) GROUP BY `main_table`.`entity_id`) AS `shell_request` WHERE (main_table.customer_id = '22') UNION ALL SELECT `main_table`.`entity_id`, `main_table`.`increment_id`, `main_table`.`customer_id`, `main_table`.`created_at`, `main_table`.`grand_total`, `main_table`.`order_currency_code`, `main_table`.`store_id`, `main_table`.`billing_name`, `main_table`.`shipping_name`, `shell_request`.* FROM `enterprise_sales_order_grid_archive` AS `main_table` WHERE (main_table.customer_id = '22')) AS `a`

#0 /ssddata/www/www.hayley.co.uk/lib/Varien/Db/Statement/Pdo/Mysql.php(110): Zend_Db_Statement_Pdo->_execute(Array)
#1 /ssddata/www/www.hayley.co.uk/app/code/core/Zend/Db/Statement.php(291): Varien_Db_Statement_Pdo_Mysql->_execute(Array)
#2 /ssddata/www/www.hayley.co.uk/lib/Zend/Db/Adapter/Abstract.php(480): Zend_Db_Statement->execute(Array)
#3 /ssddata/www/www.hayley.co.uk/lib/Zend/Db/Adapter/Pdo/Abstract.php(238): Zend_Db_Adapter_Abstract->query('SELECT COUNT(*)...', Array)
#4 /ssddata/www/www.hayley.co.uk/lib/Varien/Db/Adapter/Pdo/Mysql.php(504): Zend_Db_Adapter_Pdo_Abstract->query('SELECT COUNT(*)...', Array)
#5 /ssddata/www/www.hayley.co.uk/lib/Zend/Db/Adapter/Abstract.php(828): Varien_Db_Adapter_Pdo_Mysql->query('SELECT COUNT(*)...', Array)
#6 /ssddata/www/www.hayley.co.uk/lib/Varien/Data/Collection/Db.php(225): Zend_Db_Adapter_Abstract->fetchOne(Object(Varien_Db_Select), Array)
#7 /ssddata/www/www.hayley.co.uk/lib/Varien/Data/Collection.php(225): Varien_Data_Collection_Db->getSize()
#8 /ssddata/www/www.hayley.co.uk/lib/Varien/Data/Collection.php(211): Varien_Data_Collection->getLastPageNumber()
#9 /ssddata/www/www.hayley.co.uk/lib/Varien/Data/Collection/Db.php(522): Varien_Data_Collection->getCurPage()
#10 /ssddata/www/www.hayley.co.uk/lib/Varien/Data/Collection/Db.php(569): Varien_Data_Collection_Db->_renderLimit()
#11 /ssddata/www/www.hayley.co.uk/app/code/core/Mage/Adminhtml/Block/Widget/Grid.php(533): Varien_Data_Collection_Db->load()
#12 /ssddata/www/www.hayley.co.uk/app/code/core/Mage/Adminhtml/Block/Customer/Edit/Tab/Orders.php(61): Mage_Adminhtml_Block_Widget_Grid->_prepareCollection()
#13 /ssddata/www/www.hayley.co.uk/app/code/core/Mage/Adminhtml/Block/Widget/Grid.php(626): Mage_Adminhtml_Block_Customer_Edit_Tab_Orders->_prepareCollection()
#14 /ssddata/www/www.hayley.co.uk/app/code/core/Mage/Adminhtml/Block/Widget/Grid.php(632): Mage_Adminhtml_Block_Widget_Grid->_prepareGrid()
#15 /ssddata/www/www.hayley.co.uk/app/code/core/Mage/Core/Block/Abstract.php(918): Mage_Adminhtml_Block_Widget_Grid->_beforeToHtml()
#16 /ssddata/www/www.hayley.co.uk/app/code/core/Mage/Core/Block/Text/List.php(43): Mage_Core_Block_Abstract->toHtml()
#17 /ssddata/www/www.hayley.co.uk/app/code/core/Mage/Core/Block/Abstract.php(919): Mage_Core_Block_Text_List->_toHtml()
#18 /ssddata/www/www.hayley.co.uk/app/code/local/Inchoo/PHP7/Model/Layout.php(15): Mage_Core_Block_Abstract->toHtml()
#19 /ssddata/www/www.hayley.co.uk/app/code/core/Mage/Core/Controller/Varien/Action.php(390): Inchoo_PHP7_Model_Layout->getOutput()
#20 /ssddata/www/www.hayley.co.uk/app/code/core/Mage/Adminhtml/controllers/CustomerController.php(437): Mage_Core_Controller_Varien_Action->renderLayout()
#21 /ssddata/www/www.hayley.co.uk/app/code/core/Mage/Core/Controller/Varien/Action.php(418): Mage_Adminhtml_CustomerController->ordersAction()
#22 /ssddata/www/www.hayley.co.uk/app/code/core/Mage/Core/Controller/Varien/Router/Standard.php(254): Mage_Core_Controller_Varien_Action->dispatch('orders')
#23 /ssddata/www/www.hayley.co.uk/app/code/core/Mage/Core/Controller/Varien/Front.php(172): Mage_Core_Controller_Varien_Router_Standard->match(Object(Mage_Core_Controller_Request_Http))
#24 /ssddata/www/www.hayley.co.uk/app/code/core/Mage/Core/Model/App.php(365): Mage_Core_Controller_Varien_Front->dispatch()
#25 /ssddata/www/www.hayley.co.uk/app/Mage.php(683): Mage_Core_Model_App->run(Array)
#26 /ssddata/www/www.hayley.co.uk/index.php(82): Mage::run('', 'store')
#27 {main}
"

**Comment by icurdinj** [comment]
Do what they say. Disable the extension, and when the error happens again, send them the new stack trace, without Inchoo_PHP7 in it...

**Comment by durzel** [comment]
What on earth is "shell_request" in that SQL query?.... 

I can't find any reference at all to "shell_request" anywhere in CE 1.9.2.4.  Is that something specific to EE?

The term "shell_request" is ringing all kinds of alarm bells for me...

**Comment by hgpit** [comment]
No idea what "shell_request" is, sorry :)

But if we disable the Inchoo plugin, we still get the same error.

I am just manually removing all the Inchoo files instead of just disabling and will re-test.

Thank you for your replies, guys!

**Comment by hgpit** [comment]
@durzel, you are a god! Pointing out "shell_request" as being suspicious  led me right to the culprit. It was an extension we had which enabled various "tweaks" in the back-end. One of which was providing more details in the order management.

Thank you very much for your input :)

Best Regards,

Elliot
