### ISSUE TITLE
Abstract.php errors, can't get Magento 1.9.2.4 working with php7

### ISSUE THREAD

**Issue by soydemadrid** [Inchoo/Inchoo_PHP7#67]
Hi I hope you can please help. My site just has the white screen of death both on the backend and frontend...

I get these errors in Apache after applying your patch to try get the site to work:

`mod_fcgid: stderr: Stack trace:
mod_fcgid: stderr: #0 /home/public_html/app/code/core/Mage/Core/Block/Messages.php(80): Mage_Core_Model_Session_Abstract->getMessages(true)
mod_fcgid: stderr: #1 /home/public_html/app/code/core/Mage/Core/Block/Abstract.php(293): Mage_Core_Block_Messages->_prepareLayout()
mod_fcgid: stderr: #2 /home/public_html/app/code/local/Mage/Core/Model/Layout.php(456): Mage_Core_Block_Abstract->setLayout(Object(Inchoo_PHP7_Model_Layout))
mod_fcgid: stderr: #3 /home/public_html/app/code/local/Mage/Core/Model/Layout.php(472): Mage_Core_Model_Layout->createBlock('core/messages', 'messages')
mod_fcgid: stderr: #4 /home/public_html/app/code/local/Mage/Core/Model/Layout.php(239): Mage_Core_Model_Layout->addBlock('core/messages', 'messages')
mod_fcgid: stderr: #5 /home/public_html/app/code/local/Mage/Core/Model/Layout.php(205): Mage_Core_Model_Layout->_generateBlock(Object(Mage_Core_Model_Layout_El in /home/public_html/app/code/core/Mage/Core/Model/Session/Abstract.php on line 214
`

Any help really appreciated thanks :)

**Comment by icurdinj** [comment]
Did you try this: [https://github.com/Inchoo/Inchoo_PHP7/wiki/ProperInstallation](https://github.com/Inchoo/Inchoo_PHP7/wiki/ProperInstallation)?

**Comment by soydemadrid** [comment]
Hi thanks. I just followed the guide here: 

https://support.hypernode.com/knowledgebase/php-7/

and installed with:
```
curl -L https://github.com/Inchoo/Inchoo_PHP7/archive/master.tar.gz | \
    tar xvz -C ~/public_html Inchoo_PHP7-master/app --strip-components=1
```

I'm not really sure how to use modman, but tried your wiki command ./modman repair which gives me these errors:

```
./modman repair
./modman: line 2: app/code/local/Inchoo/PHP7: Is a directory
./modman: line 5: app/etc/modules/Inchoo_PHP7.xml: Permission denied
./modman: line 8: app/code/local/Mage/Connect/Packager.php: Permission denied
./modman: line 9: app/code/local/Mage/Core/Model/File/Uploader.php: Permission denied
./modman: line 10: app/code/local/Mage/Core/Model/Resource/Session.php: Permission denied
```

Thanks again for any help getting this set up.

**Comment by icurdinj** [comment]
If you installed files with tar, you don't need modman. But, it seems like you might have some file permission problems there?

**Comment by soydemadrid** [comment]
Hi thanks. All my permissions are set as I normally do with files being 0644 and directories 0755...

My other sites work ok this way with fastcgi, but this site always gives me these errors:

`mod_fcgid: stderr: Stack trace: mod_fcgid: stderr: #0 /home/public_html/app/code/core/Mage/Core/Block/Messages.php(80): Mage_Core_Model_Session_Abstract->getMessages(true) mod_fcgid: stderr: #1 /home/public_html/app/code/core/Mage/Core/Block/Abstract.php(293): Mage_Core_Block_Messages->_prepareLayout() mod_fcgid: stderr: #2 /home/public_html/app/code/local/Mage/Core/Model/Layout.php(456): Mage_Core_Block_Abstract->setLayout(Object(Inchoo_PHP7_Model_Layout)) mod_fcgid: stderr: #3 /home/public_html/app/code/local/Mage/Core/Model/Layout.php(472): Mage_Core_Model_Layout->createBlock('core/messages', 'messages') mod_fcgid: stderr: #4 /home/public_html/app/code/local/Mage/Core/Model/Layout.php(239): Mage_Core_Model_Layout->addBlock('core/messages', 'messages') mod_fcgid: stderr: #5 /home/public_html/app/code/local/Mage/Core/Model/Layout.php(205): Mage_Core_Model_Layout->_generateBlock(Object(Mage_Core_Model_Layout_El in /home/public_html/app/code/core/Mage/Core/Model/Session/Abstract.php on line 214`

**Comment by icurdinj** [comment]
What happens when you run that site on PHP 5.6?

**Comment by soydemadrid** [comment]
Hi thanks, I just moved all the files and database over to a test server running php 5.6.24 and I'm still getting the Abstract.php line 214 error:

`PHP Fatal error:  __clone method called on non-object in /var/www/app/code/core/Mage/Core/Model/Session/Abstract.php on line 214`

**Comment by icurdinj** [comment]
Ok, now try removing Inchoo_PHP7 and see what happens then.
