### ISSUE TITLE
500 response code & Array to String conversion error

### ISSUE THREAD

**Issue by J-Fricke** [Inchoo/Inchoo_PHP7#70]
I installed this on my local dev environment and things worked well. I just attempted to get this going on a remote server more similar to our production environment and when trying to load any Magento URLs (homepage & admin tested) I get a 500 error and in the `system.log`  this is the only error I'm seeing:

`2016-09-01T17:55:57+00:00 ERR (3): Notice: Array to string conversion  in /...app/code/core/Mage/Core/Model/Layout.php on line 555`

I can echo/exit on the index.php file so that is loading.

I used composer to install both on local and on the remote server.

**Comment by J-Fricke** [comment]
I just turned on error reporting and this is now showing up on the screen:
`Fatal error: Uncaught Error: Function name must be a string in /.../app/code/core/Mage/Core/Model/Layout.php on line 555`

**Comment by J-Fricke** [comment]
Even further when I `var_dump()` in that file the `$callback` variable I get this output just before the fatal: 

```
array (size=2)
  0 => string 'root' (length=4)
  1 => string 'toHtml' (length=6)
```

All strings.

I just remembered one of the possible breaking changed and tried this:
`$out .= $this->getBlock($callback[0])->$callback[1]();`
becomes this:
`$out .= $this->getBlock($callback[0])->{$callback[1]}();`

And things load. Now the question is what went wrong with my installation or how does this get fixed without me modifying a core file.

**Comment by icurdinj** [comment]
Most probable reason: you have Magento caches turned off on your local, and turned on on your remote. You didn't clear the caches on remote after installation.

**Comment by J-Fricke** [comment]
It's possible that it was a cache issue and I will test this out when I get a chance, but my fix does not seem to indicate cache to me since it involved grouping that $callback[1] variable with the array key using the {}.

**Comment by J-Fricke** [comment]
I will point this out as being my fix which addresses an incompatibility as seen from PHP.net:
Expression: `$foo->$bar['baz']()`	
PHP5: `$foo->{$bar['baz']}()`	
PHP7: `($foo->$bar)['baz']()`
From:
http://php.net/manual/en/migration70.incompatible.php

**Comment by J-Fricke** [comment]
I checked cache on my remote, it was enabled from some testing of the site. I turned off all cache, flushed both Magento and Storage cache's. I then reverted my change to the Layout.php file and it still gives the error:

`Fatal error: Uncaught Error: Function name must be a string in /.../app/code/core/Mage/Core/Model/Layout.php on line 555`

Re-applying the change and it works again.

**Comment by J-Fricke** [comment]
Ok, I apologize, I didn't move my installation properly. My symlink for the app/etc/modules file was linking to nothing. Once I get that sorted everything should be gtg.

**Comment by J-Fricke** [comment]
Yes confirmed, I'm all good now.
