### ISSUE TITLE
Product Attribute not save, show error.

### ISSUE THREAD

**Issue by raj-zealous** [Inchoo/Inchoo_PHP7#72]
Hi Team,

after upgrading PHP version to PHP 7, in our current project we got lots of error and by installing Inchoo_PHP7 extension fixed almost all error but still we get error while saving product attribute as "Decoding failed: Syntax error".

Please guide us to fix issue.

Thank you in advance.

**Comment by icurdinj** [comment]
Can you describe the exact way to replicate this error? I can't reproduce it. And, by the way, do you have 3rd party extensions on this project which do something with product attributes?
