### ISSUE TITLE
Fix for incorrect sorting in the calculation of the discount

### ISSUE THREAD

**Issue by herveguetin** [Inchoo/Inchoo_PHP7#73]
Hi, 

First of all: thanks a lot for this module!

Now, I am a bit confused about the "Fix for incorrect sorting in the calculation of the discount" lines in config.xml. Actually, I don't really get what this has to do with PHP7 compatibility. It looks more like a fix that is not related to PHP7.

Could you please give a little explanation on this?
Thanks again.

**Comment by icurdinj** [comment]
[https://github.com/Inchoo/Inchoo_PHP7/wiki/TotalsCalculation](https://github.com/Inchoo/Inchoo_PHP7/wiki/TotalsCalculation)
