### ISSUE TITLE
API bug in 1.9.3 with PHP7

### ISSUE THREAD

**Issue by bubach** [Inchoo/Inchoo_PHP7#79]
As per this StackOverflow post, the new 1.9.3 version (only?) have a problem with the XML RPC response and PHP7 support:

http://magento.stackexchange.com/questions/140761/soap-connection-problems-after-1-9-3-0-update

The fix being to patch 
`Mage_Api_Model_Server_Handler_Abstract::processingMethodResult(array $result)`

To look like this instead

```
public function processingMethodResult($result)
{
    if (is_array($result)) {
        foreach ($result as &$row) {
            if (!is_null($row) && !is_bool($row) && !is_numeric($row)) {
                if (is_array($row)) {
                    $row = $this->processingMethodResult($row);
                } else {
                    $row = $this->processingRow($row);
                }
            }
        }
    } else {
        if (!is_null($result) && !is_bool($result) && !is_numeric($result)) {
            $result = $this->processingRow($result);
        }
    }
    return $result;
}
```

Hopefully this will save someone a few hours. ;)

**Comment by tobihille** [comment]
If you have objects in your results you can use the following code:
```
/**
     * Prepare Api data for XML exporting
     * See allowed characters in XML:
     * @link http://www.w3.org/TR/2000/REC-xml-20001006#NT-Char
     *
     */
    public function processingMethodResult($result)
    {
        /*original but broken code:
        foreach ($result as &$row) {
            if (!is_null($row) && !is_bool($row) && !is_numeric($row)) {
                $row = $this->processingRow($row);
            }
        }
        return $result;
        */
        if (is_array($result)) {
            foreach ($result as $key => $row) {
                if (is_object($row))
                {
                    continue;
                }

                if (!is_null($row) && !is_bool($row) && !is_numeric($row)) {
                    if (is_array($row)) {
                        $result[$key] = $this->processingMethodResult($row);
                    }
                    else {
                        $result[$key] = $this->processingRow($row);
                    }
                }
            }
        } else {
            if (!is_null($result) && !is_bool($result) && !is_numeric($result)) {
                $result = $this->processingRow($result);
            }
        }
        return $result;
    }
```

I also had to replace ```&$row``` with ```$key => $row```. Hope this helps

**Comment by bubach** [comment]
Yeah, I'm actually using this version because I _wanted_ the extra objects to get outputted too - for example giftcard & storecredit information tied to an order.

Not that pretty, but it has some sanity-checks, for example checking if the object is inheriting from Varien_Object before processing the results from getData();   Also makes sure an array of objects is represented as an array in the XML, not struct with named object instances.

```
public function processingMethodResult($result)
{
    if (is_array($result)) {
        foreach ($result as &$row) {
            if (!is_null($row) && !is_bool($row) && !is_numeric($row)) {
                if (is_array($row)) {
                    $objectArr = false;
                    foreach ($row as &$rowitem) {
                        if (is_object($rowitem) && $rowitem instanceof Varien_Object) {
                            $rowitem = $this->processingMethodResult($rowitem->getData());
                            $objectArr = true;
                        }
                    }
                    if ($objectArr) {
                        $row = array_values($row);
                    }
                    $row = $this->processingMethodResult($row);
                } else {
                    $row = $this->processingRow($row);
                }
            }
        }
    } else {
        if (!is_null($result) && !is_bool($result) && !is_numeric($result)) {
            $result = $this->processingRow($result);
        }
    }
    return $result;
}
```

**Comment by joolswills** [comment]
Just fyi the code above from @bubach didn't work for me - see https://github.com/digitalpianism/bugfixes/issues/3#issuecomment-254574830 but the code from @tobihille did. thanks.

**Comment by bubach** [comment]
Sorry about that, never used the API with objects not inheriting from Varien_Object, but I modified the code above to support both types.

**Comment by icurdinj** [comment]
Guys, just one question - does this bug manifest on PHP 5.6 too?

**Comment by joolswills** [comment]
@icurdinj I believe so.

@bubach your modified code still doesn't work I'm afraid. (Also tagging @digitalpianism)

with your new code and `shoppingCartShippingList($sessionId, $cartId);`

```
array(4) {
  [0]=>
  object(stdClass)#3 (0) {
  }
  [1]=>
  object(stdClass)#4 (0) {
  }
  [2]=>
  object(stdClass)#5 (0) {
  }
  [3]=>
  object(stdClass)#6 (0) {
  }
}
```

Previous working code from @tobihille 

```
array(4) {
  [0]=>
  object(stdClass)#3 (6) {
    ["code"]=>
    string(46) "royalmail_UK_STANDARD_FIRST_CLASS_SMALL_PARCEL"
    ["carrier"]=>
    string(9) "royalmail"
    ["carrier_title"]=>
    string(10) "Royal Mail"
    ["method"]=>
    string(36) "UK_STANDARD_FIRST_CLASS_SMALL_PARCEL"
    ["method_title"]=>
    string(33) "Standard First Class Small Parcel"
    ["price"]=>
    float(4.04)
  }

... etc

```

**Comment by digitalpianism** [comment]
@joolswills please let me know which is the working code so I can apply to: https://github.com/digitalpianism/bugfixes/issues/3#issuecomment-254574830

**Comment by joolswills** [comment]
the code from https://github.com/Inchoo/Inchoo_PHP7/issues/79#issuecomment-254504096

I assumed there was a reason why @bubach did it differently though - and his method (although not yet working), may be preferable. I don't know as I've not looked into it closely.

**Comment by durzel** [comment]
This bug is not specific to PHP 7, it is a bug with 1.9.3.0 as confirmed here:

http://magento.stackexchange.com/questions/140810/what-is-different-between-magento-1-9-2-4-and-magento-1-9-3/140826#140826

As such it probably shouldn't be included in this extension, even though the fix is useful info and appreciated.  There are it seems a number of bugs in 1.9.3.0 that make it very likely that Magento will release 1.9.3.1 shortly.

**Comment by bjoern-tantau** [comment]
I used 

````
    public function processingMethodResult($result)
    {
        if (is_object($result) && is_callable(array($result, 'toArray'))) {
            $result = $result->toArray();
        }
        if (is_array($result)) {
            foreach ($result as &$row) {
                if (is_object($row) && is_callable(array($row, 'toArray'))) {
                    $row = $row->toArray();
                }
                if (!is_null($row) && !is_bool($row) && !is_numeric($row)) {
                    if (is_array($row)) {
                        $row = $this->processingMethodResult($row);
                    } else {
                        $row = $this->processingRow($row);
                    }
                }
            }
        } else {
            if (!is_null($result) && !is_bool($result) && !is_numeric($result)) {
                $result = $this->processingRow($result);
            }
        }
        return $result;
    }
````
That should work with Collections as well.

**Comment by icurdinj** [comment]
I agree with @durzel . This extension is not the place for this fix. But, if someone wants to start a "General Magento Core Fixes" extension, I would wholeheartedly support it. :-)

**Comment by bubach** [comment]
I simply used the first code that seemed to work for me, and have not investigated the code posted by tobihille or bjoern-tantau - either of which might be way better/stable. As far as the bugfixing module, see https://github.com/digitalpianism/bugfixes :)

**Comment by icurdinj** [comment]
@bubach , thanks for the heads-up for digitalpianism/bugfixes. That looks like a good place for this fix.

**Comment by Silarn** [comment]
There may still be a PHP 7 based bug, unless I'm missing a strange logic issue somewhere. I was tackling this bug today myself and discovered that - even if the resulting array appears identical with a dump - if the data is passed through the foreach by reference (foreach ($result as &$row)) and returned to the SoapServer, it would result in a set of empty results for certain functions. (For instance, salesOrderList.)

By modifying the foreach loop to simply use $key => $row rather than a reference, the SoapServer would return the full results as expected. (This also fixed some issues with other third party API responses, where I would sometimes see a 'missing encoding' error.)

Am I the only one with this issue? I was able to duplicate both on a running server as well as in a vagrant box with different environments. It could somehow relate to third-party modules but I didn't see anything obvious.

**Comment by bjoern-tantau** [comment]
> it would result in a set of empty results for certain functions. (For instance, salesOrderList.)
> Am I the only one with this issue?

Can't reproduce. salesOrderList is always filled for me.
