### ISSUE TITLE
EE branch update?

### ISSUE THREAD

**Issue by craigcarnell** [Inchoo/Inchoo_PHP7#81]
Hi,

Are you going to update the EE branch with the 1.14.3 changes?

Also what are the differences between EE and CE in terms of the branches?

**Comment by icurdinj** [comment]
Yes, as soon as get my hands on an EE 1.14.3 installation. In the meantime, pull requests are welcome, as always.
Using the current version of EE branch should do no harm - it probably just carries more code than needed.

**Comment by batmike** [comment]
When you say you need to get an EE 1.14.3 installation, how do you usually get those packages? If you need someone to provide them to work on and test, I'm happy to share the package.

**Comment by icurdinj** [comment]
@batmike , thanks, but I do have the package already. I need time to go through it :-)

**Comment by batmike** [comment]
@icurdinj - No problem. This has been a great addition to provide support for PHP7 to our site and things are working great!

**Comment by icurdinj** [comment]
Guys, if my tests are correct, due to fixes implemented in Magento core, there is no need for different branches for CE and EE any more - 2.0.0 release works for both.

It would be great if you can try and confirm it, too. There is no such thing as too much testing.

I'm planning to leave the EE branch as is for people who just patched 1.14.2.4 core (PHP 7 fixes are not included in SUPEE patches), and update the readme to let people know 2.0.0 release works for both CE 1.9.3 & EE 1.14.3.

**Comment by J-Fricke** [comment]
We are in the process of testing 2.0.0 release with EE currently. I'll update if I find any issues.

**Comment by J-Fricke** [comment]
We are seeing this issue with our upgrade on our one page checkout/success page where it's not displaying the info.phtml & view.phtml blocks as it should. I've isolated it to the `getChildHtml` call here being empty:

```
<?php
if (Mage::getStoreConfigFlag('checkoutsuccess/general/detailed_info')
    && Mage::registry('current_order')) :
    echo $this->getChildHtml();
endif;
?>
```

I'm unsure if this is tied to the Inchoo module, the upgrade, or something else at this point.

**Comment by icurdinj** [comment]
@J-Fricke - was your issue related to PHP 7? If it wasn't, I'll be closing this issue...

**Comment by J-Fricke** [comment]
Go ahead and close this. Mine is template related, still sorting it out, though I was able to swap to a different theme within my package and it was working, so...

**Comment by icurdinj** [comment]
Thanks for the feedback, closing.
