### ISSUE TITLE
PHP 7 and INCHOO fix + problems with item prices in the cart

### ISSUE THREAD

**Issue by tomekjordan** [Inchoo/Inchoo_PHP7#82]
Hi. Recently I found problem with PHP 7 and Inchoo and WDCA Sweet Tooth points extension.
After deep investigation I think I found the source of problems.
a). In PHP versions before 7.0.12 Inchoo fixes allowed to run M1924. finally.
b) but I had problems with WDCA Sweet Tooth Points extension - in php7+inchoo each item added, gives item price divided by number of items. funny but real. 
http://help.sweettoothrewards.com/category/3-announcements-basics

PHP 7.0.12 INCHOO fix enabled: > GIVES WRONG ITEM PRICES [http://prntscr.com/cwljos](http://prntscr.com/cwljos)
subtotal is still the same, item price is decreased with each qty added. weird.

PHP 7.0.12 INCHOO fix disabled: [http://prntscr.com/cwliux](http://prntscr.com/cwliux)

Funny thing I just found that PHP 7.0.12 and M1924 works without Inchoo fix.probably not 100% good, but at least admin login works, layout problems doesn't appear. So the problem is that Inchoo fixes some problems, but gives some another (prices with Sweet Tooth points extension).

So the problem is that Inchoo changes something in total? prices? I don;t know - can somebody take a look at this problem?

Looks like PHP 7.0.12 comparing to 7.0.0-7.0.10 changed something in sortings, that may affect price calculations.

**Comment by icurdinj** [comment]
I have a project which is still in queue to be PHP 7 enabled, and uses Sweet Tooth, so this problem is going to be investigated and fixed. Eventually. :-)

**Comment by tomekjordan** [comment]
Cool. I tested it deeply. and I think PHP 7.0.12 changed something that affect price/total sortings. ST was not working before correctly - meaning item prices were divided by qty. And this is probably Inchoo fix effect. But not in PHP 7.0.12 without Inchoo fix - prices are stable. but ST has another problem - all catalog points rules that are related to product price are calculated like it was 1 item in the cart. http://prntscr.com/cwo1p6
So I think there is some wrong in table sortings related to php7, but it changed in php 7.0.12 to other similar problem :)

**Comment by bubach** [comment]
@tomekjordan Could you try the patch I mention in issue https://github.com/Inchoo/Inchoo_PHP7/issues/80 and see if that corrects the behaviour?

**Comment by tomekjordan** [comment]
will try this patch, but https://github.com/hartmut-ltd/magento-php7-totals-fix didnt help with that case

**Comment by ajbonner** [comment]
I ran into this too, basically the collectTotals sorting bug affects sweettooth too. My solution was to (urgh) hardcode the sort order in lieu of a more permanent solution.

**Comment by tomekjordan** [comment]
@ajbonner can you share your resolution. is your ST working with php 7?

**Comment by studio2f** [comment]
I just want to chime in and add that i'm having Magento CE 1.9.3/PHP7.0.6/SweetTooth troubles as well. When PHP7 is enabled, SweetTooth isn't properly calculating the total points. In the shot below, the points should be 149. Disabling PHP7(reverting to PHP5.6) and the points calculate correctly.

![point problem](https://dl.dropboxusercontent.com/u/8230194/points/Screen%20Shot%202016-10-25%20at%202.57.49%20PM.png)

**Comment by ajbonner** [comment]
@tomekjordan My fix is gross and I'm not proud of it but basically I moved  
app/code/core/Mage/Sales/Model/Config/Ordered.php to the local code pool and in ```    protected function _getSortedCollectorCodes()```

I supplied a manually sorted collectors list for the quote_collectors

```
 if ($this->_collectorsCacheKey == 'sorted_quote_collectors') {
            return array(
                'rewardspent',
                'rewards',
                'nominal',
                'rewardearned',
                'subtotal',
                'freeshipping',
                'rewardshipping',
                'tax_subtotal',
                'msrp',
                'weee',
                'discount',
                'shipping',
                'tax_shipping',
                'tax',
                'grand_total'
            );
        }
```

So the full method now looks like this


```php
    /**
     * Aggregate before/after information from all items and sort totals based on this data
     *
     * @return array
     */
    protected function _getSortedCollectorCodes()
    {
        if ($this->_collectorsCacheKey == 'sorted_quote_collectors') {
            return array(
                'rewardspent',
                'rewards',
                'nominal',
                'rewardearned',
                'subtotal',
                'freeshipping',
                'rewardshipping',
                'tax_subtotal',
                'msrp',
                'weee',
                'discount',
                'shipping',
                'tax_shipping',
                'tax',
                'grand_total'
            );
        }

        if (Mage::app()->useCache('config')) {
            $cachedData = Mage::app()->loadCache($this->_collectorsCacheKey);
            if ($cachedData) {
                return unserialize($cachedData);
            }
        }
        $configArray = $this->_modelsConfig;
        // invoke simple sorting if the first element contains the "sort_order" key
        reset($configArray);
        $element = current($configArray);
        if (isset($element['sort_order'])) {
            uasort($configArray, array($this, '_compareSortOrder'));
        } else {
            foreach ($configArray as $code => $data) {
                foreach ($data['before'] as $beforeCode) {
                    if (!isset($configArray[$beforeCode])) {
                        continue;
                    }
                    $configArray[$code]['before'] = array_unique(array_merge(
                        $configArray[$code]['before'], $configArray[$beforeCode]['before']
                    ));
                    $configArray[$beforeCode]['after'] = array_merge(
                        $configArray[$beforeCode]['after'], array($code), $data['after']
                    );
                    $configArray[$beforeCode]['after'] = array_unique($configArray[$beforeCode]['after']);
                }
                foreach ($data['after'] as $afterCode) {
                    if (!isset($configArray[$afterCode])) {
                        continue;
                    }
                    $configArray[$code]['after'] = array_unique(array_merge(
                        $configArray[$code]['after'], $configArray[$afterCode]['after']
                    ));
                    $configArray[$afterCode]['before'] = array_merge(
                        $configArray[$afterCode]['before'], array($code), $data['before']
                    );
                    $configArray[$afterCode]['before'] = array_unique($configArray[$afterCode]['before']);
                }
            }
            uasort($configArray, array($this, '_compareTotals'));
        }
        $sortedCollectors = array_keys($configArray);
        if (Mage::app()->useCache('config')) {
            Mage::app()->saveCache(serialize($sortedCollectors), $this->_collectorsCacheKey, array(
                    Mage_Core_Model_Config::CACHE_TAG
                )
            );
        }
        return $sortedCollectors;
    }
```

This is a very brittle. naive, solution to the problem and not at all recommended. On our platform we have very few 3rd party modules and full control over the whole application stack, but it's on my list to fix correctly by implementing a topological sort algorithm as per http://stackoverflow.com/questions/9194281/sort-algorithm-magento-checkout-totals-sorted-wrongly-causing-wrong-shipping-ta

There is an outstanding (and unaddressed) bug report in Magento for this. At this point I don't think it will be fixed in core and indeed fixing it could well break a lot of stores that rely on the incorrect behavior.

**Comment by tomekjordan** [comment]
@ajbonner your solution probably will not help with Sweet Tooth Catalog rules and price dividing with each item increase in the cart.
@studio2f you have problem with sorting. but if you also use ST Catalog rules - you will get both problems in totals as well.

**Comment by bubach** [comment]
I had both types of problems, the topological sort patch as I've mentioned before, from issue https://github.com/Inchoo/Inchoo_PHP7/issues/80 fixed both. It's very easy to apply with git or hg and will automatically put the modified file in the local code pool. Apparently all sorts of weird shit can happen when the ordering is off in just the "right" way.

**Comment by OnyXxL** [comment]
I have that issue with PHP 7.0.13 and magento CE 1.9.3.1. It seems that doesn't only affect users of Sweet Tooth Points extension. I'm not even sure it is Inchoo PHP7 related because my Magento installation now works without PHP7 plugin.

**Comment by icurdinj** [comment]
@tomekjordan & everyone else in this discussion: topological sort, which should fix price calculation with all 3rd party extensions is now implemented in master branch and 1.9.2.4 branch.
If you can, please test on projects where you had problems previously and give feedback before we make a release.

**Comment by icurdinj** [comment]
I believe this is solved in the new releases.

**Comment by tomekjordan** [comment]
Hi. Strange but in M1931 and Php 7.1 or 7.0.15 everything works well even without your extension :) Sweet Tooth Rewards also... strange, but works.
