### ISSUE TITLE
Fatal error: Uncaught Error: Function name must be a string in app/code/core/Mage/Core/Model/Layout.php:555

### ISSUE THREAD

**Issue by marove2000** [Inchoo/Inchoo_PHP7#84]
Thank you for your Patch! I'm getting the error:

`Fatal error: Uncaught Error: Function name must be a string in app/code/core/Mage/Core/Model/Layout.php:555`

 Problem still exists after patching magento with your patch. The Patch in https://www.atwix.com/magento/magento-and-php-7/ is fixing the problem.

**Comment by jensvandorpe** [comment]
I have the same issue,
I saw in the changelog "all model overwrites - they are no longer needed.".

But it seems the layout overwrite is still needed.

**Comment by icurdinj** [comment]
https://github.com/Inchoo/Inchoo_PHP7/wiki/ProperInstallation

**Comment by daanisatis** [comment]
On what version of Magento are you? If you don't have Magento 1.9.3, you need to use the 1.0.6 release.
(And don't forget to clear your cache folder)

**Comment by marove2000** [comment]
@daanisatis 1.9.3 and yes, I've cleared the cache folder ;).

**Comment by Insect2015** [comment]
@marove2000 Please run the command n98-magerun.phar dev:module:rewrite:conflicts in your ssh and place the output over here please.
