### ISSUE TITLE
Session management

### ISSUE THREAD

**Issue by quartarian** [Inchoo/Inchoo_PHP7#88]
I noticed some unexpected behavior with session management. When using PHP7, I could not reliably log in as a customer **while** logged in as an admin. When using the customer login form, it reliable required 2 attempts. However programmatically I could not login as a customer while logged in as an admin at all.

I know this is an oddly specific use case, and it certainly doesn't need fixed for me, but I thought I would mention it in case this caused other wonky behavior regarding sessions.

**Comment by J-Fricke** [comment]
We migrated our sessions to Redis to avoid issues with Memcache. You may want to consider this as well, worth testing to see if your issue persists.

**Comment by quartarian** [comment]
@J-Fricke Thanks for your suggestion. Turns our we weren't even using memcache. ¯\_(ツ)_/¯ I've updated the OP.

At any rate, for this client, being able to login as an administrator and client at the same time was critical so I reverted them back to PHP 5.
