### ISSUE TITLE
Uninstall

### ISSUE THREAD

**Issue by bignick44** [Inchoo/Inchoo_PHP7#89]
Hi,

The fix works fine for me but im migrating to a server using bitnami and php 5.
How do i remove this fix? Just change from true to false in the xml as with plugins?

Thank you!

**Comment by icurdinj** [comment]
Yes, that should be enough, but even if you don't disable it, this extension should not break anything on PHP 7.

**Comment by bignick44** [comment]
Great!
No it didnt break anything on php7 but im downgrading to php5.

**Comment by icurdinj** [comment]
My mistake, I wanted to say it should not break anything on PHP 5 either :-)
