### ISSUE TITLE
Payment method sort order not working as expected. 

### ISSUE THREAD

**Issue by duffner** [Inchoo/Inchoo_PHP7#93]
I'm working on a Magento EE project using PayPal Payflow Pro payment method, along with check / mo and PayPal Express enabled.   For some reason the admin input for "Sort Order" is not working as expected.  When the project is run on php5.6 there isn't an issue, when changed to php7 it appears to be quite random in it's presentation.    Within my local environment I switched php versions and sort order would restore when php version was 5.6 and not function on php7

**Comment by icurdinj** [comment]
Nice catch, I'll look into it as soon as I find some time.

**Comment by duffner** [comment]
Awesome! Thanks.

**Comment by duffner** [comment]
Is there any update on this particular bug?

**Comment by icurdinj** [comment]
Actually, this does work as expected. You just need to put a _different_ number in each _Sort Order_ field, and the payment methods will be sorted by their numbers.

**Comment by duffner** [comment]
Hi,  

I believe the issue is specific to PayPal payflow pro payment method. I will document steps more thouroughly later today.  The offline payment methods work correctly it appears.

**Comment by icurdinj** [comment]
Ok, please do.

**Comment by icurdinj** [comment]
@duffner , do you have the steps to reproduce the issue?

**Comment by AndrewFelipe** [comment]
@icurdinj i get this issue with specific cart rule for specific payment method. Magento calculates discount after it defines grand_total so grand_total amount is wrong.

I used this _patch_: http://stackoverflow.com/a/11954867/2620326
But as i need to correct another issues i tried your code with topological sort and it works like a charm!
