### ISSUE TITLE
Unmaintained server?

### ISSUE THREAD

**Issue by doublezeroseven** [Inchoo/Inchoo_PHP7#95]
hi, after installing magento on php 7, all patches are green (according to: https://www.magereport.com )

but "Unmaintained server?" status shows "unknown"

and magento-check.php tool shows:

You need PHP 5.2.0 (or greater)'; } else { $pass .='
You have PHP 5.2.0 (or greater)
'; } if(!ini_get('safe_mode')) { $pass .='
Safe Mode is off
'; preg_match('/[0-9]\.[0-9]+\.[0-9]+/', shell_exec('mysql -V'), $version); if(version_compare($version[0], '4.1.20', '<')) { $fail .= '
You need MySQL 4.1.20 (or greater)
'; } else { $pass .='
You have MySQL 4.1.20 (or greater)
'; } } else { $fail .= '
Safe Mode is on
'; } foreach($extensions as $extension) { if(!extension_loaded($extension)) { $fail .= '
You are missing the '.$extension.' extension
'; } else{ $pass .= '
You have the '.$extension.' extension
'; } } if($fail) { echo '

Your server does not meet the following requirements in order to install Magento.'; echo '
The following requirements failed, please contact your hosting provider in order to receive assistance with meeting the system requirements for Magento:'; echo '

    '.$fail.'

'; echo 'The following requirements were successfully met:'; echo '

    '.$pass.'

'; } else { echo '

Congratulations! Your server meets the requirements for Magento.
'; echo '

    '.$pass.'

'; } } ?>

is this normal? :/

**Comment by icurdinj** [comment]
Yes, it's normal, as these tools don't recognize that you can run M 1 on PHP 7 :-)

**Comment by Mic2005** [comment]
I run M1 on PHP7 but magereport.com does not give unmaintained server when
i scan. You can contact byte.nl or leave a suggestion on the magereport.com
site.
